/**
 * Pure Markdown renderer for ClauseWise export output.
 *
 * Kept entirely separate from the API call layer so it can be:
 *   1. Unit-tested without any mocks or network access.
 *   2. Reused by a future PDF/DOCX export feature without touching routes.
 *   3. Audited independently of prompt logic (separation of concerns).
 *
 * No I/O, no side effects, no imports from external packages.
 * All functions are pure: same input always produces same output.
 */

import type { Persona } from "../services/decisionEngine.js";
import type { DocumentType } from "../prompts/classify.js";

// ── Types ──────────────────────────────────────────────────────────────────────

/** All data needed to render the export Markdown. */
export interface ExportRenderInput {
  documentType: DocumentType;
  persona: Persona;
  summary: string;
  checklist: string[];
  /** Combined list: Gemini-generated questions + folded out-of-scope questions. */
  lawyerQuestions: string[];
  /** ISO date string, e.g. "2025-09-14" — injected by caller for testability. */
  date: string;
}

// ── Helpers ────────────────────────────────────────────────────────────────────

/**
 * Convert a snake_case persona identifier to a readable label.
 * "small_business_owner" → "Small Business Owner"
 * "unknown"              → "General Reader"
 */
function personaLabel(persona: Persona): string {
  if (persona === "unknown") return "General Reader";
  return persona
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

/**
 * Convert a snake_case document type to a readable label.
 * "employment_contract"     → "Employment Contract"
 * "loan_or_vendor_agreement" → "Loan / Vendor Agreement"
 */
function docTypeLabel(documentType: DocumentType): string {
  // Title-case each word, then replace the "_or_" connector with " / ".
  return documentType
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("_")
    .replace(/_Or_/g, " / ")
    .replace(/_/g, " ");
}

// ── Main renderer ──────────────────────────────────────────────────────────────

/**
 * Render the export data as a Markdown string suitable for display or download.
 *
 * Output format:
 * ```
 * # ClauseWise Export — Employment Contract
 * **Persona:** Employee | **Generated:** 2025-09-14
 *
 * ## Document Summary
 * ...
 *
 * ## Action Checklist
 * - [ ] Read the notice period clause...
 * - [ ] Negotiate the non-compete scope...
 *
 * ## Questions for Your Lawyer
 * 1. Under clause 8.3, can the employer terminate without cause?
 * 2. Is the 12-month non-compete enforceable in this jurisdiction?
 *
 * ---
 * *⚠ This document is generated by ClauseWise for informational purposes only
 * and does not constitute legal advice. Consult a qualified lawyer before
 * acting on any of the above.*
 * ```
 *
 * @param input  Validated export data (checklist and questions already deduplicated).
 * @returns      A UTF-8 Markdown string.
 */
export function renderExportMarkdown(input: ExportRenderInput): string {
  const { documentType, persona, summary, checklist, lawyerQuestions, date } = input;

  const typeLabel = docTypeLabel(documentType);
  const pLabel = personaLabel(persona);

  const lines: string[] = [];

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push(`# ClauseWise Export — ${typeLabel}`);
  lines.push(`**Persona:** ${pLabel} | **Generated:** ${date}`);
  lines.push("");

  // ── Document Summary ────────────────────────────────────────────────────────
  lines.push("## Document Summary");
  lines.push("");
  lines.push(summary.trim());
  lines.push("");

  // ── Action Checklist ────────────────────────────────────────────────────────
  lines.push("## Action Checklist");
  lines.push("");
  if (checklist.length === 0) {
    lines.push("*(No checklist items generated.)*");
  } else {
    for (const item of checklist) {
      // GitHub-flavoured Markdown task list syntax.
      lines.push(`- [ ] ${item.trim()}`);
    }
  }
  lines.push("");

  // ── Lawyer Questions ────────────────────────────────────────────────────────
  lines.push("## Questions for Your Lawyer");
  lines.push("");
  if (lawyerQuestions.length === 0) {
    lines.push("*(No lawyer questions generated.)*");
  } else {
    lawyerQuestions.forEach((q, i) => {
      lines.push(`${i + 1}. ${q.trim()}`);
    });
  }
  lines.push("");

  // ── Disclaimer ──────────────────────────────────────────────────────────────
  lines.push("---");
  lines.push(
    "*⚠ This document is generated by ClauseWise for informational purposes only " +
      "and does not constitute legal advice. Consult a qualified lawyer before " +
      "acting on any of the above.*",
  );

  return lines.join("\n");
}
